import ctypes
user32 = ctypes.windll.user32

FPS = 60
SCREEN_WIDTH = user32.GetSystemMetrics(0)
SCREEN_HEIGHT = user32.GetSystemMetrics(1)

CARD_RISE = int(SCREEN_HEIGHT*0.125)

HAND_HEIGHT = int(SCREEN_HEIGHT*1.05)
HAND_SPACE = int(SCREEN_WIDTH*0.6)
HAND_MARGIN = int(SCREEN_WIDTH*0.2)

PLACE_HEIGHT = int(SCREEN_HEIGHT*0.7)
PLACE_SPACE = int(SCREEN_WIDTH*0.7)
PLACE_MARGIN = int(SCREEN_WIDTH*0.15)