import ctypes
user32 = ctypes.windll.user32

FPS = 60
SCREEN_WIDTH = user32.GetSystemMetrics(0)
SCREEN_HEIGHT = user32.GetSystemMetrics(1)
# SCREEN_WIDTH = 1920
# SCREEN_HEIGHT = 1080

CARD_RISE = int(SCREEN_HEIGHT*0.25)

HAND_HEIGHT = int(SCREEN_HEIGHT*0.925)
HAND_SPACE = int(SCREEN_WIDTH*0.6)
HAND_MARGIN = int(SCREEN_WIDTH*0.15)

PLACE_HEIGHT = int(SCREEN_HEIGHT*0.7)
PLACE_SPACE = int(SCREEN_WIDTH*0.7)
PLACE_MARGIN = int(SCREEN_WIDTH*0.15)